package(default_visibility = ["//visibility:public"])

java_library(
    name = "sorts",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/jeffmanzione/sortinggui/sorts/business",
    ],
)
