package(default_visibility = ["//visibility:public"])

java_library(
    name = "graphics",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/jeffmanzione/sortinggui/graphics/exceptions",
        "//java/com/jeffmanzione/sortinggui/sorts",
        "//java/com/jeffmanzione/sortinggui/sorts/business",
        "@maven//:org_openjfx_javafx_base_win",
        "@maven//:org_openjfx_javafx_controls_win",
        "@maven//:org_openjfx_javafx_graphics_win",
    ],
)
